use_frameworks!

target 'AllUniteSdk_Example' do
  pod 'AllUniteSdk', :path => '../'

  target 'AllUniteSdk_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
